# Generated by Django 4.1.1 on 2022-12-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Position',
            field=models.CharField(default='Position', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='Team', max_length=255),
        ),
    ]
